services:
  eliza:
    command: ["pnpm", "start", "--character=./characters/eliza.character.json"]
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./data:/app/data
    environment:
      - SERVER_PORT=3000
    ports:
      - "3000:3000"
    restart: always
